require 'test/unit'
require 'test/test_basic'
require 'test/test_random'
require 'test/test_coderefs'
require 'test/test_path_like_variable_scope'
require 'test/test_realloc'
require 'test/test_register'
require 'test/test_html_template_pro'
